global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files: []

scrape_configs:

  # ðŸ”¹ Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']

  # ðŸ”¹ API Gateway
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8222']

  # ðŸ”¹ Config Server
  - job_name: 'config-server'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8888']

  # ðŸ”¹ Eureka Server
  - job_name: 'eureka'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8761']

  # ðŸ”¹ Customer Service
  - job_name: 'customer-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8090']

  # ðŸ”¹ Product Service
  - job_name: 'product-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8050']

  # ðŸ”¹ Order Service
  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8070']

  # ðŸ”¹ Payment Service
  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8060']

  # ðŸ”¹ Notification Service
  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8040']